# This file is no longer used, it is kept for reference.
version: 2.1

restore-workspace: &restore-workspace
  attach_workspace:
    at: ~/

publish-filter: &publish-filter
  branches:
    only: master

gh-pages-filter: &gh-pages-filter
  branches:
    ignore: gh-pages

executors:
  node:
    docker:
      - image: circleci/node:12.9.0-browsers
    working_directory: ~/aircall-everywhere

jobs:
  checkout-install-node-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: aircall-everywhere-node-modules{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: aircall-everywhere-node-modules{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: ~/
          paths: aircall-everywhere

  test:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn test

  coverage:
    executor: node
    steps:
      - *restore-workspace
      - run: sudo apt-get install libjq1 jq bc
      - run: yarn coverage
      - run:
          name: Publish coverage on PR
          command: |
            export PATH="$PATH:~/.local/bin"
            bash ./scripts/post-coverage-to-github.sh $CIRCLE_BRANCH

  build-prod:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths: aircall-everywhere/dist

  npm-publish:
    executor: node
    steps:
      - *restore-workspace
      - add_ssh_keys:
          fingerprints:
            - '39:31:4b:93:fd:ea:b3:65:09:c9:d7:20:9f:8d:87:dd'
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/aircall-everywhere/.npmrc
      - run: git config --global user.email "alan.chauchet@gmail.com"
      - run: git config --global user.name "Alan Chauchet"
      - run: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout-install-node-dependencies
      - test:
          requires: [checkout-install-node-dependencies]
          filters: *gh-pages-filter

      - coverage:
          requires: [test]
          filters:
            branches:
              ignore: gh-pages
                master

      - build-prod:
          requires: [test]
          filters: *gh-pages-filter

      - approve-publish:
          type: approval
          requires: [build-prod]
          filters: *publish-filter

      - npm-publish:
          requires: [approve-publish]
          filters: *publish-filter
